// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class YoutubeMusicTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC01Login() {
    // Test name: TC#01 - Login
    // Step # | name | target | value
    // 1 | open | https://music.youtube.com/ | 
    driver.get("https://music.youtube.com/");
    // 2 | click | css=.VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .WpHeLc | 
    driver.findElement(By.cssSelector(".VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc > .WpHeLc")).click();
    // 3 | click | css=.ibdqA > .lCoei | 
    driver.findElement(By.cssSelector(".ibdqA > .lCoei")).click();
  }
  @Test
  public void tC02CreateanewPlaylist() {
    // Test name: TC#02 - Create a new Playlist
    // Step # | name | target | value
    // 1 | open | https://music.youtube.com/ | 
    driver.get("https://music.youtube.com/");
    // 2 | click | css=.style-scope:nth-child(3) > .tab-title | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(3) > .tab-title")).click();
    // 3 | click | css=.ytmusic-grid-renderer:nth-child(1) #img | 
    driver.findElement(By.cssSelector(".ytmusic-grid-renderer:nth-child(1) #img")).click();
    // 4 | type | css=#input-6 > .style-scope | Playlist 3
    driver.findElement(By.cssSelector("#input-6 > .style-scope")).sendKeys("Playlist 3");
    // 5 | type | id=textarea | playchill
    driver.findElement(By.id("textarea")).sendKeys("playchill");
    // 6 | click | css=.style-primary #button | 
    driver.findElement(By.cssSelector(".style-primary #button")).click();
    // 7 | end |  | 
  }
  }
  @Test
  public void tC03Addasong() {
    // Test name: TC#03 - Add a song
    // Step # | name | target | value
    // 1 | open | https://music.youtube.com/ | 
    driver.get("https://music.youtube.com/");
    // 2 | click | css=.style-scope:nth-child(1) > .menu > #button > #icon | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(1) > .menu > #button > #icon")).click();
    // 3 | click | linkText=Add to playlist | 
    driver.findElement(By.linkText("Add to playlist")).click();
    // 4 | verifyElementPresent | css=.style-scope:nth-child(2) > .style-scope > .information-container > #title | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".style-scope:nth-child(2) > .style-scope > .information-container > #title"));
      assert(elements.size() > 0);
    }
    // 5 | click | css=.ytmusic-add-to-playlist-renderer:nth-child(3) > .ytmusic-playlist-add-to-option-renderer | 
    driver.findElement(By.cssSelector(".ytmusic-add-to-playlist-renderer:nth-child(3) > .ytmusic-playlist-add-to-option-renderer")).click();
    // 6 | verifyElementPresent | css=#text > .style-scope:nth-child(1) | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#text > .style-scope:nth-child(1)"));
      assert(elements.size() > 0);
    }
    // 7 | end |  | 
  }
  }
}
